name: Deploy Flask App

on:
    workflow_run:
        workflows: ["docker build and push"] # removed extra space ✅
        types: [completed]

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }} # added ✅

        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER22 }}
            DOCKER_TAG: ${{ github.sha }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Deploy with Docker Compose
              run: docker compose down && docker compose up -d --build --force-recreate --pull always
