name: docker build and push
on:
    workflow_dispatch:
    # push:
    #     branches:
    #         - main
jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: checkout the code
              uses: actions/checkout@v4

            - name: login to dockerhub
              uses: docker/login-action@v3
              with:
                  username: ${{vars.DOCKERHUB_USER22}}
                  password: ${{secrets.DOCKERHUB_TOKEN22}}

            - name: build and push to DockerHub
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: |
                      ${{vars.DOCKERHUB_USER22}}/github-action-advanced:${{github.ref_name}}
                      ${{vars.DOCKERHUB_USER22}}/github-action-advanced:latest
                      ${{vars.DOCKERHUB_USER22}}/github-action-advanced:${{ github.sha}}
